services:
  scoring-api:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"